### ISSUE TITLE
Could not find the required component 'spencer_nav_msgs'

### ISSUE THREAD

**Issue by airjohnson** [srl-freiburg/srl_rhcf_planner#4]
Hi,
    I'm trying to install the srl_rhcf_planner package. I've installed spencer_people_tracking package successfully. When I was use catkin_make to build the package, error occurred.
    I really appreciate your help. Thanks a lot!

The error is as following:

CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "spencer_nav_msgs"
  with any of the following names:

    spencer_nav_msgsConfig.cmake
    spencer_nav_msgs-config.cmake

  Add the installation prefix of "spencer_nav_msgs" to CMAKE_PREFIX_PATH or
  set "spencer_nav_msgs_DIR" to a directory containing one of the above
  files.  If "spencer_nav_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  srl_rhcf_planner/CMakeLists.txt:6 (find_package)

-- Could not find the required component 'spencer_nav_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "spencer_nav_msgs"
  with any of the following names:

    spencer_nav_msgsConfig.cmake
    spencer_nav_msgs-config.cmake

  Add the installation prefix of "spencer_nav_msgs" to CMAKE_PREFIX_PATH or
  set "spencer_nav_msgs_DIR" to a directory containing one of the above
  files.  If "spencer_nav_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  srl_rhcf_planner/CMakeLists.txt:6 (find_package)

**Comment by palmieri** [comment]
Hi, 

you need to install spencer_nav_msgs which you can find in spencer_messages package, you can find it here: https://github.com/spencer-project/spencer_messages.

Sorry for the late answer. 

Best

**Comment by airjohnson** [comment]
Hi,
    Thank you for your help. I installed spencer_nav_msgs as you said, and it works. But another error occurred while I was building the package.
    The error is as follows, I guess CollisionStatus.h must be missing.
    Best wishes!

Zhang Sen
zhangs@mail.nankai.edu.cn
Institute of Robotics & Automatic Information System
Nankai University, Tianjin, China

在 2016-11-03 03:06:30，Luigi Palmieri notifications@github.com 写道：
Hi,
you need to install spencer_nav_msgs which you can find in spencer_messages package, you can find it here: https://github.com/spencer-project/spencer_messages.
Sorry for the late answer.
Best

**Comment by KuanqiCai** [comment]
hi 
i install the spencer_messages as you said, but i can't find the spencer_nav_msgs. could you please give me a hand?

**Comment by BoLeiChen** [comment]
hi
I can't find the spencer_nav_msgs,too. could you please give me a hand?

**Comment by adi-0906** [comment]
same here, can't find it. It doesn't  exist in https://github.com/spencer-project/spencer_messages.  Please help.
thanks in advance!

**Comment by crisdeodates** [comment]
For those who were unable to solve this: I have found a solution.

It seems like they changed the message structure to ais their latest works.
Do the following after you clone the repository

1. cd into the repository
2. Execute this command: "**git checkout fef6a8bf3d8bc3bcdf3dfc91b35046c12d998be3**"

Now build your main project as usual. It will work :)
